---
resources:
  - name: ci-pipeline
    type: git
    source:
      uri: https://github.com/surverohan/concource-ci-springboot-ebeanstalk.git
      branch: master

  - name: graphql-src
    type: git
    source:
      uri: https://github.com/surverohan/graphqlc.git
      branch: master

  - name: graphql-artifact
    type: s3
    source:
      bucket: graphql-storage
      region_name: us-east-1
      versioned_file: graphql-poc.jar
      access_key_id: ((aws-key-id))
      secret_access_key: ((aws-access-key))

jobs:
  - name: build-graphql-app
    build_logs_to_retain: 30
    plan:
      - aggregate:
        - get: ci-pipeline
        - get: graphql-src
          trigger: true
      - task: build
        file: ci-pipeline/tasks/build/build.yml
      - put: graphql-artifact
        params:
          file: build/graphql-poc.jar
          name: graphql-poc.jar

  - name: deploy-graphql-app
    serial: true
    plan:
      - aggregate:
        - get: ci-pipeline
        - get: graphql-artifact
          passed:
            - build-graphql-app
          trigger: true
      - task: create-env
        file: ci-pipeline/tasks/deploy/deploy.yml
        params:
          APPLICATION_NAME: graphql-app
          ENVIRONMENT_NAME: graphql-env
          CNAME: graphql-env
          AWS_ACCESS_KEY_ID: ((aws-key-id))
          AWS_SECRET_ACCESS_KEY: ((aws-access-key))

groups:
  - name: graphql-app
    jobs:
      - build-graphql-app
      - deploy-graphql-app
