---
resources:
  - name: pipeline-src
    type: git
    source:
      uri: https://github.com/surverohan/concource-ci-springboot-ebeanstalk.git
      branch: master

  - name: demo-app-src
    type: git
    source:
      uri: https://github.com/pmilianbeto/elasticbeanstalk-demo-app.git
      branch: master

  - name: demo-app-artifact
    type: s3
    source:
      bucket: demo-app-ops
      region_name: us-east-1
      versioned_file: demo-app.jar
      access_key_id: ((aws-key-id))
      secret_access_key: ((aws-access-key))

jobs:
  - name: build-demo-app
    build_logs_to_retain: 30
    plan:
      - aggregate:
        - get: pipeline-src
        - get: demo-app-src
          trigger: true
      - task: build
        file: pipeline-src/tasks/build/build.yml
      - put: demo-app-artifact
        params:
          file: build/demo-app.jar
          name: demo-app.jar

  - name: deploy-demo-app
    serial: true
    plan:
      - aggregate:
        - get: pipeline-src
        - get: demo-app-artifact
          passed:
            - build-demo-app
          trigger: true
      - task: create-env
        file: pipeline-src/tasks/deploy/deploy.yml
        params:
          APPLICATION_NAME: demo-app
          ENVIRONMENT_NAME: demo-app-env
          CNAME: demo-app-env
          AWS_ACCESS_KEY_ID: ((aws-key-id))
          AWS_SECRET_ACCESS_KEY: ((aws-access-key))

groups:
  - name: demo-app_1
    jobs:
      - build-demo-app
      - deploy-demo-app
