---
platform: linux

image_resource:
  type: docker-image
  source: { repository: betomorrow/docker-awsebcli }

inputs:
  - name: pipeline-src
  - name: demo-app-artifact

run:
  path: pipeline-src/tasks/deploy/deploy.sh
